CFLAGS = -Wall -Wextra -g

day_07: src/day_07.cpp Makefile
	clang++ src/day_07.cpp -o day_07 $(CFLAGS) && ./day_07

day_08: src/day_08.c Makefile
	clang src/day_08.c -o day_08 $(CFLAGS) && ./day_08
	
